### ISSUE TITLE
User "locked_out_user" cannot login

### ISSUE THREAD

**Issue by pramam** [pramam/webdriverio-saucedemo-testing#4]
The user "locked_out_user" cannot login with the provided password "secret_sauce"
(scroll down to see 2 images)
![image](https://user-images.githubusercontent.com/57686495/152095401-589c71f6-b252-46e9-8b1e-7559a6ba49d2.png)
Error message:
![image](https://user-images.githubusercontent.com/57686495/152095537-b08dd4d1-f200-479c-ae29-fbd11ccc0ebf.png)

**Comment by ckenst** [comment]
Why is this a bug?

**Comment by pramam** [comment]
Closing this as it is not a bug.
