### ISSUE TITLE
"About" page takes you to a new domain name

### ISSUE THREAD

**Issue by pramam** [pramam/webdriverio-saucedemo-testing#5]
Logging into https://www.saucedemo.com/ and clicking on the 'About' page takes you to a different domain.

Steps to reproduce:
- Go to https://www.saucedemo.com
![image](https://user-images.githubusercontent.com/57686495/152101560-98940e83-c769-48aa-8232-7f9aa42197f4.png)

- Login as a valid user (username: 'standard_user', password: 'secret_sauce')
- Click on Burger menu on top left
- Click on 'About' in the options shown
- It takes you to a new domain https://saucelabs.com/ (image below)
![image](https://user-images.githubusercontent.com/57686495/152101467-1b5eac47-83e2-4e32-9018-0b206c538db2.png)

**Comment by ckenst** [comment]
Why is this a bug?

**Comment by pramam** [comment]
Closing this.
